// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stfpxofeanlzshmhemfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0ZnB4b2ZlYW5senNobWhlbWZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NzAwNTcsImV4cCI6MjA2MDI0NjA1N30.3zm6XGEUKoJdMrNz5pmaJulWi2lpkMRU02OSqMjVOcc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);